development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3    
  pool: 5
  timeout: 5000
  
test:
  adapter: sqlite3
  encoding: unicode
  database: db/test.sqlite3    
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['db_n']%>
  pool: 5
  username: <%= ENV['db_un']%>
  password: <%= ENV['db_pass']%>